modLoader="javafml"
loaderVersion="[47,)"
license="Academic Free License v3.0"

[[mods]]
modId="doctor_nowhere"
version="1.6.0"
displayName="Doctor Nowhere mod"
displayURL="https://modrinth.com/mod/doctor-nowhere"
logoFile="logo.png"
credits="made by ishakirabotaem"
authors="ishakirabotaem"
description="Adds doctor nowhere's creatures."

[[dependencies.doctor_nowhere]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"



[[dependencies.doctor_nowhere]]
    modId="geckolib"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"

